'use client'

import type { Metadata } from "next";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import 'swiper/css'
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/app/utils/theme";
import { CacheProvider } from "@emotion/react";
import cacheRtl from "@/app/utils/cacheRtl";
import { CustomToastContainer } from "@/app/components/Toast/styles";

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html dir={ 'rtl' } lang="en">
        <body>
        <AppRouterCacheProvider>
            <CacheProvider value={ cacheRtl }>
                <ThemeProvider theme={ theme }>
                    { children }

                    <CustomToastContainer/>
                </ThemeProvider>
            </CacheProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
